### ISSUE TITLE
MPR

### ISSUE THREAD

**Issue by ahmad565565** [Mihapro/MP-Reporter#1]
I have some problems.
1st The addon report death sometimes when the player is low hp not when the Player Dies
2nd In some of my alts not reporting anything at all I've tried to reactivate it and still not working
3rd some times Death reporter report the death twice in raid chat
Idea.
Would be nice if you make Some kind of raid warnings enable/disable
Also I'm not experience  with writing codes I want to Add some Warnings for Example at marrow " Kill Spike " and at LK When someone is grabbed say in RW "PlayerName Is grabbed" 
Sorry for my English it's not my Main language

**Comment by Mihc3** [comment]
Hopefully fixed in 2ee4b2731396924bbabb114ac1c2c949a4f3f7f8. About your alt characters, not sure what could be wrong. Try toggling /MPR settings and see if you manage to get it working.

See [MPR.lua:1048](https://github.com/Mihapro/MP-Reporter/commit/2ee4b2731396924bbabb114ac1c2c949a4f3f7f8#diff-46b77f06f2a913f84dbd739aa6161fc8R1048) and [MPR.lua:1448](https://github.com/Mihapro/MP-Reporter/commit/2ee4b2731396924bbabb114ac1c2c949a4f3f7f8#diff-46b77f06f2a913f84dbd739aa6161fc8R1448). I have added lines that you just have to uncomment (remove "--") to get the warnings you requested working.

**Comment by ahmad565565** [comment]
It's working perfectly <3 also as i notice that you only added two raid warnings that i've told you as example, I'll try to cover all the raidwarnings i meant so if you can update it later :
ICC
Lord Marrow:-
spike warning  _already done_ 
Lady:-
Mind control ( CC MC People )
When adds appears ( Stop dpsing boss and kill adds )
Rotface:-
When ozze explode ( ozze explode gtfo )
Putricide:-
Gas bomb (Bottles in the floor Gtfo)
Green ooze (Stack)
Red Ooze (Red ooze's target Kite )
Council:-
When the debuff on Kele (No aoe near Kele)
Queen:-
Before Terror with 5 secs ( Fear is coming Gtfo from flames )
Sindra:-
_Track if someone is exploding on raid_
At 3rd Phase ( stack at right side-marked person go left side )
Lk:-
Plague (Plague on NAME)
Valks _already done_
Defile in like 5 secs (Defile in 5 sec Spread)
Spirits ( Spirits coming, watch out )

RS
Halion:-
Meteor strike ( Switch to other side )
start of 2nd phase ( Don't enter before tank )
Cutter (Cutter coming in 5 sec) and after cutter(Move back)
Toc
Twins: 
When to switch target and when to use Def CDS

I'm sorry for the Long request list, also I know some people doesn't use the same tactics if it's possible to do it private if you don't want to use it for global release

**Comment by ahmad565565** [comment]
Death reporter, reporting "player name dead" but he's still alive

**Comment by Mihc3** [comment]
Really? Because now it's printing it out only when server sends UNIT_DIED event to client's combat log. Do you know what ability killed the player?

**Comment by ahmad565565** [comment]
I'll try to take screenshot and post it here 
Also it's not usually like that it work perfectly some times and miss sometimes

**Comment by Mihc3** [comment]
For custom raid warnings, check functions in [MPR_Timers.lua](https://github.com/Mihapro/MP-Reporter/blob/master/MPR/MPR_Timers.lua#L477). There you can insert the following line

``` Lua
MPR:RaidWarning("Say something!")
```

Example

``` Lua
function MPR_Timers:RuneOfBlood()
    --local cd = round(self.DataTimers[4][1],1,true)
    --if cd > 0 then self:NewTimer(GetSpellLink(self:GetSpellID("Rune of Blood")),cd,nil) end
    self.DataTimers[4][1] = 18
    MPR:RaidWarning("Taunt!!")
end
```

Note that summon wave/adds at Lady Deathwhisper isn't accurate (cooldowns unknown and also different in each difficulty on Molten), so better not putting add announce there.

**Comment by Mihc3** [comment]
Fixed. 280cfeae68a6c663b2a9b4fd920e4d69ea64d1bf
